fixed spacing

diff --git a/post_chroot b/post_chroot
--- a/post_chroot
+++ b/post_chroot
@@ -6,13 +6,13 @@ hwclock --systohc
 # Localization
 echo "Setting localization"
 sed -i 's/#en_US.UTF-8 UTF-8\en_US.UTF-8 UTF-8/' /etc/locale.gen
-echo LANG=en_US.UTF-8 >> /etc/locale.conf
+echo LANG=en_US.UTF-8 >>/etc/locale.conf
 locale-gen
 
 # Hostname/Network configuration
 echo "Configuring hostname/network"
 read -rp "Type Hostname > " HOSTNAME
-echo "$HOSTNAME" >> /etc/hostname
+echo "$HOSTNAME" >>/etc/hostname
 
 echo "# <ip-address>    <hostname.domain.org>   <hostname>"
 echo "127.0.0.1         localhost >> /etc/hosts"
@@ -39,19 +39,22 @@ Please Select:
   read -rp "Enter selection [0-1] > "
 
   case "$REPLY" in
-    0)	echo "Continue installation."
-      break
-      ;;
-    1)	echo "User creation"
-      read -rp "Type user name > " username
-      read -rp "Type user password > " userpwd
-      useradd -m -G wheel video "$username"
-      echo -e "$userpwd\n$userpwd" | passwd "$username"
-      sleep 2
-      ;;
-    *)	echo "Invalid entry" >&2
-      continue
-      ;;
+  0)
+    echo "Continue installation."
+    break
+    ;;
+  1)
+    echo "User creation"
+    read -rp "Type user name > " username
+    read -rp "Type user password > " userpwd
+    useradd -m -G wheel video "$username"
+    echo -e "$userpwd\n$userpwd" | passwd "$username"
+    sleep 2
+    ;;
+  *)
+    echo "Invalid entry" >&2
+    continue
+    ;;
   esac
 done
 sed -i 's/^# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers
@@ -68,13 +71,13 @@ sed -i 's/#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf
 ##############
 
 pacman --needed -Sy git pacman-contrib fwupd man-db man-pages texinfo systemd-resolvconf nm-connection-editor wireguard-tools tar libarchive \
-binutils bzip2 gzip lzop xz zstd p7zip unrar zip unzip xarchiver curl tree exa bat wget exfat-utils bash-completion
+  binutils bzip2 gzip lzop xz zstd p7zip unrar zip unzip xarchiver curl tree exa bat wget exfat-utils bash-completion
 
 #######################
 ##XDG Directory setup##
 #######################
 
-tee -a /etc/security/pam_env.conf > /dev/null <<EOT
+tee -a /etc/security/pam_env.conf >/dev/null <<EOT
 XDG_DATA_HOME    DEFAULT=@{HOME}/.local/share
 XDG_CONFIG_HOME  DEFAULT=@{HOME}/.config
 XDG_CACHE_HOME   DEFAULT=@{HOME}/.cache
@@ -93,7 +96,7 @@ EOT
 if [[ $BOOT == 'uefi' ]]; then
   bootctl install
   touch /boot/loader/entries/arch-zen.conf
-  tee -a /boot/loader/entries/arch-zen.conf > /dev/null <<EOT
+  tee -a /boot/loader/entries/arch-zen.conf >/dev/null <<EOT
   title Arch Linux Zen
   linux /vmlinuz-linux-zen
   initrd /intel-ucode.img
@@ -113,7 +116,7 @@ fi
 pacman --needed --noconfirm -S fail2ban
 cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
 touch /var/log/auth.log
-tee -a /etc/fail2ban/jail.local > /dev/null <<EOT
+tee -a /etc/fail2ban/jail.local >/dev/null <<EOT
 [ssh]
 enabled = true
 port = ssh
@@ -138,7 +141,7 @@ systemctl enable fstrim.timer
 
 ## Finishing touches document create
 touch /home/"$username"/finishing-touches.txt
-tee -a /home/"$username"/finishing-touches.txt > /dev/null <<EOT
+tee -a /home/"$username"/finishing-touches.txt >/dev/null <<EOT
 Verify '/etc/default/grub' is setup right for hibernation
 then run 'grub-mkconfig -o /boot/grub/grub.cfg' for proper setup
 
